Create ci.yml
exercism/pharo-smalltalk pull request #427
Opened 2020-10-22 07:24 UTC by samWson

Fixes #425 

As with the rest of Exercism we are migrating CI from Travis to Github Actions.

For reviewer reference smalltalkCI is a tool specifically for running CI pipelines on Smalltalk dialects. We are using [their Github Action](https://github.com/marketplace/actions/setup-smalltalkci). It makes use of this [STON ](https://github.com/exercism/pharo-smalltalk/blob/master/.smalltalk.ston) (a Smalltalk JSON equivalent) file in our repo to decide which tests to run.

I've tried to map what our existing [Travis file](https://github.com/exercism/pharo-smalltalk/blob/master/.travis.yml) does to this workflow but I'm not an expert in either tool.

2020-10-22 09:06 UTC, ErikSchierboom approved these changes
This looks good! Just some copy/paste comments.

2020-10-22 09:06 UTC, ErikSchierboom commented on .github/workflows/ci.yml
> +        runs-on: ubuntu-latest
```suggestion
```

2020-10-22 09:06 UTC, ErikSchierboom commented on .github/workflows/ci.yml
> +        runs-on: ubuntu-latest
```suggestion
```

2020-10-22 14:05 UTC, cmccandless requested changes

2020-10-22 14:05 UTC, cmccandless commented on .github/workflows/ci.yml
> +        uses: hpi-swa/setup-smalltalkCI@v1
It's best practice to target specific commit hashes over tags: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
```suggestion
        uses: hpi-swa/setup-smalltalkCI@a271ee530f18ecf947856f3f163c4687101ec6b6
```

2020-10-22 14:05 UTC, cmccandless commented on .github/workflows/ci.yml
> +        uses: hpi-swa/setup-smalltalkCI@v1
Exceptions to this are: official actions (`actions/*`) and those you control (`exercism/github-actions/*`)

2020-10-22 14:05 UTC, cmccandless commented on .github/workflows/ci.yml
> +on: [push, pull_request]
To avoid duplicate builds, I recommend this instead:
```suggestion
on:
  push:
    branches: [master]
  pull_request:
```

2020-10-23 07:26 UTC, samWson commented
@ErikSchierboom @cmccandless thanks for the review and suggested changes. I've made the changes and the latest run of the action seems to do everything we want it to. If your both happy I'll get this merged and start another issue to remove the redundant Travis and configlet scripts.

2020-10-23 09:04 UTC, ErikSchierboom commented
Yes, LGTM!

2020-10-23 12:33 UTC, cmccandless approved these changes

2020-10-24 07:04 UTC, merged