Update installation scripts to reference `main` branch instead of `ma…
exercism/pharo-smalltalk pull request #474
Opened 2021-04-21 08:18 UTC by samWson

These installation scripts got missed when fixes were made because of the shift from `master` to `main` as the primary development branch.

2021-04-21 08:25 UTC, samWson commented
Hold on merging this PR. I thought the installation scripts were not up to date.

At least two people have been having errors installing because the installation scripts on the Exercism website still look like this:
```smalltalk
Iceberg remoteTypeSelector: #httpsUrl.
Metacello new 
 baseline: 'Exercism'; 
 repository: 'github://exercism/pharo-smalltalk/releases/latest';
 load.
 
#ExercismManager asClass welcome.
```

The `repository` part of that script should read like this: ` repository: 'github://exercism/pharo-smalltalk:main/releases/latest'`.
And it does in the installation documentation: https://github.com/exercism/pharo-smalltalk/blob/main/docs/INSTALLATION.md

At a guess the current version of the Exercism website is not talking updates from the repository anymore due to the imminent release of Exercism V3.

2021-04-21 08:43 UTC, Bajger commented
Hi Sam, I think it is because Exercism-Smalltalk is probably not released with updated version of MD from main (done by @edward ). I guess someone from original authors @macta can do this?

2021-04-21 08:49 UTC, samWson commented
@Bajger I think it's just the installation script.

When people who have had this issue try again with the script as it is in the repository they don't have any problems installing.

2021-04-21 09:12 UTC, Bajger commented
Installation script is ok (as seen in https://github.com/exercism/pharo-smalltalk/blob/main/docs/INSTALLATION.md), but Exercism Pharo website (https://exercism.io/tracks/pharo/installation) uses version from release of this md file, but not actual version from main. Therefore I think new release of this project will make the change propagated to Exercism website.

2021-04-21 09:14 UTC, Bajger commented
See https://github.com/exercism/pharo-smalltalk/releases/  - last update was in 2019.

2021-04-21 15:07 UTC, SleeplessByte commented
cc @iHiD 

Could be that the name change didn't sync up. I've tagged Jeremy to confirm. It's also possible that _even_ if you do a new release that it isn't synced, and he'll have to manually push it to unbreak the site for pharo users.

Is there a release planned to check if that would solve it?

2021-04-21 15:08 UTC, SleeplessByte commented on docs/INSTALLATION.md
> +From time to time we may need you to update the libraries in your Pharo Exercism image. Please follow [these instructions](https://github.com/exercism/pharo-smalltalk/blob/master/docs/UPGRADE.md)
```suggestion
From time to time we may need you to update the libraries in your Pharo Exercism image. Please follow [these instructions](https://github.com/exercism/pharo-smalltalk/blob/main/docs/UPGRADE.md)
```

2021-04-24 23:56 UTC, samWson commented
Doing a bit more investigation into this. @iHiD suggested making a `master` branch that mimics `main`. I'll give that a go since it's quick to do. Then I'll have a look into the releases. I don't really know how they fit into this repo and I haven't given them any attention until now.

For clarity here is the error:
![error-installing-exercism](https://user-images.githubusercontent.com/13286932/115975960-4af67580-a5bd-11eb-8c51-8749232d1ccb.png)

2021-04-24 23:57 UTC, samWson commented on docs/INSTALLATION.md
> +From time to time we may need you to update the libraries in your Pharo Exercism image. Please follow [these instructions](https://github.com/exercism/pharo-smalltalk/blob/master/docs/UPGRADE.md)
Thanks.

2021-04-25 00:09 UTC, samWson commented
I've just created a `master` branch which is identical to `main`. I've tested the installation script again (from the Exercism website) and it works on Windows. I also fetched an exercise and ran the tests. No problems.

This PR should still get merged because you found a reference to `master` @SleeplessByte.

I still don't know what the releases are for since I've never used them. They don't seem to be used at all by the installation script given that making a `master` branch fixed the issue. I presume they are a way to download a Pharo image that already has exercism installed.

@exercism/reviewers could I please get an approval for this PR?

2021-04-25 00:20 UTC, kotp requested changes
Trailing white space should not be introduced.

2021-04-25 00:20 UTC, kotp commented on docs/INSTALLATION.md
> + baseline: 'Exercism';
Trailing white space introduced.
```suggestion
Metacello new
 baseline: 'Exercism';
```

2021-04-25 00:20 UTC, kotp commented on docs/INSTALLATION.md
> + baseline: 'Exercism';
```suggestion
Metacello new
 baseline: 'Exercism';
```
Trailing white space introduced.

2021-04-25 00:20 UTC, kotp commented on docs/INSTALLATION.md
> +
```suggestion

```

Trailing white space introduced.

2021-04-25 00:37 UTC, SleeplessByte approved these changes

2021-04-25 06:45 UTC, kotp approved these changes

2021-04-26 03:45 UTC, merged