Wayback link for Smalltalk with style pdf
exercism/pharo-smalltalk pull request #636
Opened 2024-06-27 00:45 UTC by kotp

First commit is for style consistency, second is actual helpful update
to link.

- **Style consistency**
- **Link: Update link to reference wayback machine**

2024-06-27 19:35 UTC, kotp commented
It looks like the broken link was temporary, as it is working today.

Let me know if you still want the first patch.

2024-06-28 05:54 UTC, Bajger requested changes
I made few suggestions. Anyway, thanks for your contribution!

2024-06-28 05:54 UTC, Bajger commented on docs/CONTRIBUTING.md
> +![Pharo](http://pharo.org/web/files/pharo.png)
You can replace all Pharo site links with `https` (some browsers might block unencrypted link)

2024-06-28 05:54 UTC, Bajger commented on docs/LEARNING.md
>  * [Pharo Main Site](http://pharo.org/documentation):
same as above

2024-06-28 05:54 UTC, Bajger commented on docs/LEARNING.md
> +* [Pharo Syntax Cheatsheet](http://files.pharo.org/media/pharoCheatSheet.pdf):
one more

2024-06-28 05:54 UTC, Bajger commented on docs/LEARNING.md
>  * [Deep Into Pharo](http://books.pharo.org/deep-into-pharo/):
one more

2024-06-28 05:54 UTC, Bajger commented on docs/LEARNING.md
>  * [Enterprise Pharo - Web Perspective](http://books.pharo.org/enterprise-pharo/):
one more

2024-06-28 05:54 UTC, Bajger commented on docs/RESOURCES.md
>  * [Pharo Syntax Cheatsheet](http://files.pharo.org/media/pharoCheatSheet.pdf)
one more

2024-06-28 05:54 UTC, Bajger commented on docs/RESOURCES.md
>  * [Pharo Community Resources](http://pharo.org/community) (including Discord chat link)
one more

2024-06-28 05:54 UTC, Bajger commented on docs/RESOURCES.md
>  * [Contribute to Pharo](http://pharo.org/contribute)
one more

2024-06-28 05:54 UTC, Bajger commented on docs/RESOURCES.md
>  * [Deep Into Pharo](http://books.pharo.org/deep-into-pharo/)
one more

2024-06-28 05:54 UTC, Bajger commented on docs/RESOURCES.md
>  * [Smalltalk Grammar](https://gist.github.com/sin3141592/602700)
This one is invalid as well, but probably this is better resource? https://learnxinyminutes.com/docs/smalltalk/

2024-06-28 05:55 UTC, Bajger commented
@kotp Hi Victor! I guess you could use also link to Inria site resource: https://rmod-files.lille.inria.fr/FreeBooks/WithStyle/SmalltalkWithStyle.pdf, but I'm not sure, which one is more reliable (probably webarchive)?

2024-06-28 07:02 UTC, kotp commented on docs/RESOURCES.md
>  * [Smalltalk Grammar](https://gist.github.com/sin3141592/602700)
This one I did not change, since I do not know what the gist had for content, and so no idea if it is better or even different.

2024-06-28 07:05 UTC, kotp commented
> @kotp Hi Victor! I guess you could use also link to Inria site resource: https://rmod-files.lille.inria.fr/FreeBooks/WithStyle/SmalltalkWithStyle.pdf, but I'm not sure, which one is more reliable (probably webarchive)?

I suppose I could, but would rather link to the live version if it is stable, since any updates the author would wish to make we would gain the benefit of.

The updated link has been restored, but the http secure protocol has been updated for pharo.org links.

2024-06-28 07:25 UTC, Bajger commented on docs/RESOURCES.md
>  * [Smalltalk Grammar](https://gist.github.com/sin3141592/602700)
I'll try to get in touch with Tim MacKinnon, but I don't give much chances he'd remember :)

2024-06-28 07:25 UTC, Bajger approved these changes

2024-06-28 08:00 UTC, merged